local M = { id="AURORA_BEAM", name="Aurora Beam" }

M.soundIds = {175,176}

-- Canonical FireRed Move_AURORA_BEAM.
M.script = {
  { op="loadspritegfx", tag=10140 }, -- ANIM_TAG_RAINBOW_RINGS
  { op="fadetobg", bg="aurora" },
  { op="waitbgfadein" },
  { op="playsewithpan", sound=175, pan="attacker" },
  { op="setarg", index=7, value=0 },
  { op="createvisualtask", task="AnimTask_RotateAuroraRingColors", priority=10, args={130} },

  -- AuroraBeamCreateRings x1 (4 rings, one frame apart).
  { op="createsprite", template="gAuroraBeamRingSpriteTemplate", anchor="target", priority=2, args={20,0,0,0,17} },
  { op="delay", frames=1 },
  { op="createsprite", template="gAuroraBeamRingSpriteTemplate", anchor="target", priority=2, args={20,0,0,0,17} },
  { op="delay", frames=1 },
  { op="createsprite", template="gAuroraBeamRingSpriteTemplate", anchor="target", priority=2, args={20,0,0,0,17} },
  { op="delay", frames=1 },
  { op="createsprite", template="gAuroraBeamRingSpriteTemplate", anchor="target", priority=2, args={20,0,0,0,17} },
  { op="delay", frames=1 },

  { op="createvisualtask", task="AnimTask_ShakeMon2", priority=5, args={"target",1,0,17,1} },
  { op="createsprite", template="gAuroraBeamRingSpriteTemplate", anchor="target", priority=2, args={20,0,0,0,17} },
  { op="delay", frames=1 },
  { op="createsprite", template="gAuroraBeamRingSpriteTemplate", anchor="target", priority=2, args={20,0,0,0,17} },
  { op="delay", frames=1 },
  { op="createsprite", template="gAuroraBeamRingSpriteTemplate", anchor="target", priority=2, args={20,0,0,0,17} },
  { op="delay", frames=1 },
  { op="createsprite", template="gAuroraBeamRingSpriteTemplate", anchor="target", priority=2, args={20,0,0,0,17} },
  { op="delay", frames=1 },
  { op="createsprite", template="gAuroraBeamRingSpriteTemplate", anchor="target", priority=2, args={20,0,0,0,17} },
  { op="delay", frames=1 },
  { op="createsprite", template="gAuroraBeamRingSpriteTemplate", anchor="target", priority=2, args={20,0,0,0,17} },
  { op="delay", frames=1 },
  { op="createsprite", template="gAuroraBeamRingSpriteTemplate", anchor="target", priority=2, args={20,0,0,0,17} },
  { op="delay", frames=1 },
  { op="createsprite", template="gAuroraBeamRingSpriteTemplate", anchor="target", priority=2, args={20,0,0,0,17} },
  { op="delay", frames=1 },
  { op="createsprite", template="gAuroraBeamRingSpriteTemplate", anchor="target", priority=2, args={20,0,0,0,17} },
  { op="delay", frames=1 },
  { op="createsprite", template="gAuroraBeamRingSpriteTemplate", anchor="target", priority=2, args={20,0,0,0,17} },
  { op="delay", frames=1 },
  { op="createsprite", template="gAuroraBeamRingSpriteTemplate", anchor="target", priority=2, args={20,0,0,0,17} },
  { op="delay", frames=1 },
  { op="createsprite", template="gAuroraBeamRingSpriteTemplate", anchor="target", priority=2, args={20,0,0,0,17} },
  { op="delay", frames=1 },

  { op="setarg", index=7, value=0xFFFF },
  { op="createsoundtask", task="SoundTask_LoopSEAdjustPanning", priority=2, args={176,"attacker","target",3,6,0,10} },
  { op="createvisualtask", task="AnimTask_ShakeMon2", priority=5, args={"target",2,0,40,1} },
  { op="createsprite", template="gAuroraBeamRingSpriteTemplate", anchor="target", priority=2, args={20,0,0,0,17} },
  { op="delay", frames=1 },
  { op="createsprite", template="gAuroraBeamRingSpriteTemplate", anchor="target", priority=2, args={20,0,0,0,17} },
  { op="delay", frames=1 },
  { op="createsprite", template="gAuroraBeamRingSpriteTemplate", anchor="target", priority=2, args={20,0,0,0,17} },
  { op="delay", frames=1 },
  { op="createsprite", template="gAuroraBeamRingSpriteTemplate", anchor="target", priority=2, args={20,0,0,0,17} },
  { op="delay", frames=1 },
  { op="createsprite", template="gAuroraBeamRingSpriteTemplate", anchor="target", priority=2, args={20,0,0,0,17} },
  { op="delay", frames=1 },
  { op="createsprite", template="gAuroraBeamRingSpriteTemplate", anchor="target", priority=2, args={20,0,0,0,17} },
  { op="delay", frames=1 },
  { op="createsprite", template="gAuroraBeamRingSpriteTemplate", anchor="target", priority=2, args={20,0,0,0,17} },
  { op="delay", frames=1 },
  { op="createsprite", template="gAuroraBeamRingSpriteTemplate", anchor="target", priority=2, args={20,0,0,0,17} },
  { op="delay", frames=1 },
  { op="createsprite", template="gAuroraBeamRingSpriteTemplate", anchor="target", priority=2, args={20,0,0,0,17} },
  { op="delay", frames=1 },
  { op="createsprite", template="gAuroraBeamRingSpriteTemplate", anchor="target", priority=2, args={20,0,0,0,17} },
  { op="delay", frames=1 },
  { op="createsprite", template="gAuroraBeamRingSpriteTemplate", anchor="target", priority=2, args={20,0,0,0,17} },
  { op="delay", frames=1 },
  { op="createsprite", template="gAuroraBeamRingSpriteTemplate", anchor="target", priority=2, args={20,0,0,0,17} },
  { op="delay", frames=1 },
  { op="createsprite", template="gAuroraBeamRingSpriteTemplate", anchor="target", priority=2, args={20,0,0,0,17} },
  { op="delay", frames=1 },
  { op="createsprite", template="gAuroraBeamRingSpriteTemplate", anchor="target", priority=2, args={20,0,0,0,17} },
  { op="delay", frames=1 },
  { op="createsprite", template="gAuroraBeamRingSpriteTemplate", anchor="target", priority=2, args={20,0,0,0,17} },
  { op="delay", frames=1 },
  { op="createsprite", template="gAuroraBeamRingSpriteTemplate", anchor="target", priority=2, args={20,0,0,0,17} },
  { op="delay", frames=1 },
  { op="createsprite", template="gAuroraBeamRingSpriteTemplate", anchor="target", priority=2, args={20,0,0,0,17} },
  { op="delay", frames=1 },
  { op="createsprite", template="gAuroraBeamRingSpriteTemplate", anchor="target", priority=2, args={20,0,0,0,17} },
  { op="delay", frames=1 },
  { op="createsprite", template="gAuroraBeamRingSpriteTemplate", anchor="target", priority=2, args={20,0,0,0,17} },
  { op="delay", frames=1 },
  { op="createsprite", template="gAuroraBeamRingSpriteTemplate", anchor="target", priority=2, args={20,0,0,0,17} },
  { op="delay", frames=1 },
  { op="createsprite", template="gAuroraBeamRingSpriteTemplate", anchor="target", priority=2, args={20,0,0,0,17} },
  { op="delay", frames=1 },
  { op="createsprite", template="gAuroraBeamRingSpriteTemplate", anchor="target", priority=2, args={20,0,0,0,17} },
  { op="delay", frames=1 },
  { op="createsprite", template="gAuroraBeamRingSpriteTemplate", anchor="target", priority=2, args={20,0,0,0,17} },
  { op="delay", frames=1 },
  { op="createsprite", template="gAuroraBeamRingSpriteTemplate", anchor="target", priority=2, args={20,0,0,0,17} },
  { op="delay", frames=1 },

  { op="waitforvisualfinish" },
  { op="restorebg" },
  { op="waitbgfadein" },
  { op="end" },
}

M.templates = {
  gAuroraBeamRingSpriteTemplate = {
    tileTag=10140, paletteTag=10140, callback="AnimAuroraBeamRings",
    oam={affine=true,objMode="normal",bpp=4,width=8,height=16},
    anim={kind="dummy",frames={{tileOffset=0,duration=1}}},
    extraTileOffsets={4},
    paletteRotations=true,
  },
}

return M
